[build]
publish = "public"
command = "yarn install && node ./esmscript.prod.mjs && hugo --gc --minify"
NETLIFY_USE_YARN = "true"
NODE_VERSION = "20.13.1"

[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"
included_files = ["./db.json", "./villains.json", "/tmp/db.json"]

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"

[context.production.environment]
HUGO_VERSION = "0.124.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
